version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./user-service/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - illawarra-network
    restart: unless-stopped

networks:
  illawarra-network:
    driver: bridge
