version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./user-service/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - illawarra-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  illawarra-network:
    driver: bridge
