version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "${SERVER_PORT:-8080}:8080"   
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_API_KEY=${API_KEY}
    env_file:
      - .env
