version: '3.8'
services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - ./:/app
      - $HOME/.m2:/root/.m2
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - API_KEY=${API_KEY}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
    env_file:
      - .env
